<option value="">Day</option>
<option value="	01	" <?php if($day1 == 01) echo 'selected="yes"'; ?>>	01	</option>
<option value="	02	" <?php if($day1 == 02) echo 'selected="yes"'; ?>>	02	</option>
<option value="	03	" <?php if($day1 == 03) echo 'selected="yes"'; ?>>	03	</option>
<option value="	04	" <?php if($day1 == 04) echo 'selected="yes"'; ?>>	04	</option>
<option value="	05	" <?php if($day1 == 05) echo 'selected="yes"'; ?>>	05	</option>
<option value="	06	" <?php if($day1 == 06) echo 'selected="yes"'; ?>>	06	</option>
<option value="	07	" <?php if($day1 == 07) echo 'selected="yes"'; ?>>	07	</option>
<option value="	08	" <?php if($day1 == 08) echo 'selected="yes"'; ?>>	08	</option>
<option value=" 09	" <?php if($day1 == 09) echo 'selected="yes"'; ?>>	09	</option>
<option value="	10	" <?php if($day1 == 10) echo 'selected="yes"'; ?>>	10	</option>
<option value="	11	" <?php if($day1 == 11) echo 'selected="yes"'; ?>>	11	</option>
<option value="	12	" <?php if($day1 == 12) echo 'selected="yes"'; ?>>	12	</option>
<option value="	13	" <?php if($day1 == 13) echo 'selected="yes"'; ?>>	13	</option>
<option value="	14	" <?php if($day1 == 14) echo 'selected="yes"'; ?>>	14	</option>
<option value="	15	" <?php if($day1 == 15) echo 'selected="yes"'; ?>>	15	</option>
<option value="	16	" <?php if($day1 == 16) echo 'selected="yes"'; ?>>	16	</option>
<option value="	17	" <?php if($day1 == 17) echo 'selected="yes"'; ?>>	17	</option>
<option value="	18	" <?php if($day1 == 18) echo 'selected="yes"'; ?>>	18	</option>
<option value="	19	" <?php if($day1 == 19) echo 'selected="yes"'; ?>>	19	</option>
<option value="	20	" <?php if($day1 == 20) echo 'selected="yes"'; ?>>	20	</option>
<option value="	21	" <?php if($day1 == 21) echo 'selected="yes"'; ?>>	21	</option>
<option value="	22	" <?php if($day1 == 22) echo 'selected="yes"'; ?>>	22	</option>
<option value="	23	" <?php if($day1 == 23) echo 'selected="yes"'; ?>>	23	</option>
<option value="	24	" <?php if($day1 == 24) echo 'selected="yes"'; ?>>	24	</option>
<option value="	25	" <?php if($day1 == 25) echo 'selected="yes"'; ?>>	25	</option>
<option value="	26	" <?php if($day1 == 26) echo 'selected="yes"'; ?>>	26	</option>
<option value="	27	" <?php if($day1 == 27) echo 'selected="yes"'; ?>>	27	</option>
<option value="	28	" <?php if($day1 == 28) echo 'selected="yes"'; ?>>	28	</option>
<option value="	29	" <?php if($day1 == 29) echo 'selected="yes"'; ?>>	29	</option>
<option value="	30	" <?php if($day1 == 30) echo 'selected="yes"'; ?>>	30	</option>